### PR TITLE
 	Tests for Elytron transformer configuration

### PR DESCRIPTION
**Pull request by zebrik**

### CODE REVIEW

**Review by honza-kasik — APPROVED** [review]
LGTM, just a very minor note: Do you think that it is best solution just to fail test with 'Assert.fail()'?

I can merge it right away...

**Comment by zebrik** [comment]
`Assert.fail()` is nasty enough to force me to fix it as soon as possible ;-)

**Comment by honza-kasik** [comment]
Ok, merging :)

**Comment by honza-kasik** [comment]
Thanks!

**Pull request merged**
