### PR TITLE
Rewriting of homepage tests after HAL-834.

### PR DESCRIPTION
**Pull request by zebrik**

### CODE REVIEW

**Comment by zebrik** [comment]
@rhatlapa please review

**Comment by rhatlapa** [comment]
HAL- 834 doesn't seem to be connected with this PR, could you provide correct JIRA issue requiring this update?

**Comment by rhatlapa** [comment]
Sorry, I looked at wrong HAL jira (I've done typo in URL)

**Comment by rhatlapa** [comment]
LGTM, mergin.

**Pull request merged**
