### PR TITLE
XA datasource pool statistics test

### PR DESCRIPTION
**Pull request by zebrik**

### CODE REVIEW

**Comment by zebrik** [comment]
@honza-kasik please review

**Review by honza-kasik — COMMENTED** [review]
Thanks! Generally LGTM, although IMO deployment sources should be more separated. I suggest either:

* move all classes including `org.jboss.hal.testsuite.test.runtime.datasource.TestEntity` and classes in `org.jboss.hal.testsuite.test.runtime.datasource.beans` package to separate package or
* ~~move all deployment classes to `src/test/resources`~~

 so they cannot be confused with test sources

EDIT: I just noticed, that the second option is not possible because of import dependencies...

**Comment by zebrik** [comment]
@honza-kasik requested change was pushed.

**Comment by honza-kasik** [comment]
Thanks! Merging!

**Pull request merged**
