### PR TITLE
Standalone RBAC tests: stabilization, making more readable and maintainable.

### PR DESCRIPTION
**Pull request by zebrik**

### CODE REVIEW

**Comment by zebrik** [comment]
@spriadka  could you please provide a review? @honza-kasik can you have a look as well if you have any time?

**Comment by honza-kasik** [comment]
@zebrik Sure, I am on it!

**Review by honza-kasik — APPROVED** [review]
LGTM, thanks!

**Comment by spriadka** [comment]
Looks good

**Pull request merged**
