### PR TITLE
Update to be suitable for Wildfly9/EAP7.

### PR DESCRIPTION
**Pull request by zebrik**

### CODE REVIEW

**Comment by zebrik** [comment]
@rhatlapa @mkrajcov please look at this

**Comment by heiko-braun** [comment]
just saw your comment. did you want to hold back the merge until @rhatlapa @mkrajcov commented on it?

**Comment by zebrik** [comment]
Yes I wanted at least @rhatlapa to review this before merge.

**Comment by heiko-braun** [comment]
i did revert the change. Can you open another PR?

**Comment by heiko-braun** [comment]
sorry for the confusion and extra work

**Pull request merged**
