### PR TITLE
Fixes for logging tests and ModClusterFilterTestCase

### PR DESCRIPTION
**Pull request by honza-kasik**

### CODE REVIEW

**Comment by zebrik** [comment]
@honza-kasik  what about other logger tests related to named formatter?

**Comment by honza-kasik** [comment]
Fixed other tests for named formatter + little cleanup

**Review by zebrik — APPROVED** [review]
LGTM. Please squash a bit.

**Comment by honza-kasik** [comment]
Thanks! Merging!

**Pull request merged**
