### PR TITLE
Documment server setup for RBAC tests.

### PR DESCRIPTION
**Pull request by zebrik**

### CODE REVIEW

**Comment by zebrik** [comment]
@msmerek please review.

**Comment by zebrik** [comment]
@rhatlapa please don't merge before @msmerek 's review.

**Comment by msmerek** [comment]
I tested both domain and standalone setup and both work fine. Thank you!

**Comment by zebrik** [comment]
@rhatlapa I believe this is ready to be merged. WDYT?

**Comment by rhatlapa** [comment]
LGTM, thanks, merging

**Pull request merged**
