### PR TITLE
Checkstyle update

### PR DESCRIPTION
**Pull request by honza-kasik**
* Generates XML report
* Generates HTML site
* Also output for console
* Configuration made according to documentation
* Works for me!

### CODE REVIEW

**Comment by honza-kasik** [comment]
@zebrik WDYT?

**Comment by honza-kasik** [comment]
Just one note - we should be running only 'check' goal during 'verify' or 'validate' phase, but since it just outputs to console I used 'checkstyle'/'checkstyle-aggregate' which generates XML and HTML report instead in 'compile' phase.

**Comment by zebrik** [comment]
Looks OK. Please remove the 'Dummy fail' commit.

**Comment by honza-kasik** [comment]
Thanks, removed!

**Comment by zebrik** [comment]
Thank you!

**Pull request merged**
